### ISSUE TITLE
Qwerty and qwertz layout

### ISSUE THREAD

**Issue by Fractalzdude** [sabihoshi/GenshinLyreMidiPlayer#1]
Heya, loving it so far - however would you consider implementing a keyboard layout dropdownmenu?
Thanks <3

**Comment by sabihoshi** [comment]
I've tried testing this by changing my keyboard layout by adding a new keyboard under my language settings, but it seems to still work fine, after all it's simulating the "Z" key to press the lowest note, not "press the key to the right of L shift" or am I confused here?

I can implement it, but it seemed to have worked fine even if I changed it to QWERTZ, DVORAK, AZERTY, etc.

**Comment by Fractalzdude** [comment]
Yeah its a bit weird, when im on the QWERTZ layout the player mixes up the Z and Y, however when I switch over to the US layout and restart the game with the US layout active it is working as intended

**Comment by sabihoshi** [comment]
Well alright, regardless whether I know it works or not, I'll just add it in. It would be useful when I implement a way to create piano sheet and output it to a text file instead of playing it in the game.

**Comment by sabihoshi** [comment]
Keyboard layout support was added in [v1.3.1](https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v1.3.1)
