### ISSUE TITLE
Not an issue but can you please tell how can I play pre-made notes on the Lyre with this?

### ISSUE THREAD

**Issue by SatyamSSJ10** [sabihoshi/GenshinLyreMidiPlayer#11]
Not an issue but can you please tell me how can I play pre-made notes on the Lyre with this, if possible?

**Comment by sabihoshi** [comment]
You need what's called a MIDI file, which you can look up online. You can then load a file using the button at the top left. You have to make sure that the key is right and then just hit play.

**Comment by SatyamSSJ10** [comment]
Umm yes I know of that. I should better close this issue and create a new issue with enhancement with edit option to "piano notes"
