### ISSUE TITLE
似乎无法正常播放

### ISSUE THREAD

**Issue by KeSaite** [sabihoshi/GenshinLyreMidiPlayer#12]
v2.1.0.1版本点击播放，没有任何反应，其他版本未作尝试，也不跳转到游戏，一开始以为是必须窗口化运行，但是似乎并不是，搞不定。win10环境已安装.NET 5
> https://user-images.githubusercontent.com/13944595/126065722-68a3a461-9017-453d-be73-0283e0e8dfba.mp4

**Comment by sabihoshi** [comment]
问题的发生可能是因为进程的名称不是 "GenshinImpact.exe"，应用程序的名称是什么？在那里改完值后，你可以按照这里的说明，自己去建 https://github.com/sabihoshi/GenshinLyreMidiPlayer#build

![image](https://user-images.githubusercontent.com/25006819/126067818-5fd5e111-3a55-4db9-8d75-35b76ae81883.png)

https://github.com/sabihoshi/GenshinLyreMidiPlayer/blob/main/GenshinLyreMidiPlayer.WPF/Core/WindowHelper.cs#L10
```cs
private const string GenshinProcessName = "GenshinImpact";
```
然后你将把它改为任务管理器中看到的进程名称
```cs
private const string GenshinProcessName = "YuanShen";
```

**Comment by sabihoshi** [comment]
好消息，我刚刚对程序进行了更新，可以让你设置位置。它还应该尝试自动找到安装位置。如果成功了，请告诉我，这样我们就可以关闭.

https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v2.3.0
![image](https://user-images.githubusercontent.com/25006819/126070407-1e56f3eb-928a-4883-a43e-352fc02944e8.png)

**Comment by KeSaite** [comment]
解决了，现在正常了
