### ISSUE TITLE
俺有点懵，不知道是不是理解错了

### ISSUE THREAD

**Issue by KeSaite** [sabihoshi/GenshinLyreMidiPlayer#13]
![image](https://user-images.githubusercontent.com/13944595/127665969-02e533eb-428e-4a1b-b28f-3d614e3e8503.png)

> 按照俺对这个图标的理解：播放完当前的文件后，停止播放任何文件，不循环到下一个
实际情况：播放完当前的文件后，继续播放下一个文件

![image](https://user-images.githubusercontent.com/13944595/127666392-f366453c-ab14-4651-9652-1c7100014a99.png)

> 按照俺对这个图标的理解：播放完当前的文件后，继续重新开始播放当前文件
实际情况：播放完当前的文件后，卡在文件某一区间反复循环，而不是重新开始

**Comment by sabihoshi** [comment]
第一条将按顺序播放整个播放列表一次。我想这还不够清楚。第二个是一个错误，我正在研究。

**Comment by sabihoshi** [comment]
固定在这里 [v2.3.2](https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v2.3.2)

**Comment by KeSaite** [comment]
> 第一条将按顺序播放整个播放列表一次。我想这还不够清楚。第二个是一个错误，我正在研究。
缺少播放完一个就停止的功能按钮，感觉还是很有必要存在的。

**Comment by sabihoshi** [comment]
我在一个测试版中做了一些修改 [v2.3.3 Beta](https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v2.3.3)

**Comment by KeSaite** [comment]
> 我做了一个新的版本 [v2.3.3 Beta](https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v2.3.3)
