### ISSUE TITLE
Does not seem to work on my device

### ISSUE THREAD

**Issue by RKPinata** [sabihoshi/GenshinLyreMidiPlayer#17]
Here is the link of my experience using it:
https://youtu.be/6dHxeg3mEGE

I installed the latest standolane build. I have also tried the dependant but it wasnt showed in the video. As you can see in the video, the music doesnt play. Could it be because im using zither instead of lyre? Either ways, i've tried clicking up, down ignore but the music still doesnt play. When switching midi it also doesnt seem to work properly, it stays on the same song.

Edit: i tried using lyre instead of zither and also doesnt work

**Comment by Bloodrunk** [comment]
> It should be `GenshinImpact.exe`, not the game launcher. It should be in `C:\Program Files\Epic Games\GenshinImpact\Genshin Impact Game\GenshinImpact.exe`

I was also having the same issue (had genshin installed from epic games) and this fixed it. Thanks a lot.
