### ISSUE TITLE
Notes played are incorrect and weird.

### ISSUE THREAD

**Issue by Serakuus** [sabihoshi/GenshinLyreMidiPlayer#18]
Need some help here, please. After pressing the "play" button while having a lyre window already opened, it switches to Genshin Impact window but notes are basically super out of place and they don't match how it should go at all (presses are slow, not matching the actual tempo etc) - it has nothing to do with an actual song. Tried multiple midi files of multiple songs, even some that are played in Youtube guide videos and still no luck. 

Am I missing something?

**Comment by sabihoshi** [comment]
Did you try making sure the key, as well as the keyboard layout to be correct? And also, when the song isn't C major and only 3 octaves, and it has accidentals, the program will warn you about them. You can choose to shift them one semitone up/down so they can sound sort of correct.
