### ISSUE TITLE
Works on latest version of genshin?

### ISSUE THREAD

**Issue by Jakeisaweeb** [sabihoshi/GenshinLyreMidiPlayer#21]
Does this work on the latest version of genshin and do you get banned for using this program?

**Comment by sabihoshi** [comment]
Yes it still works, also similar question to #19 and countless more people asking the same thing on YouTube & Forums, there is a disclaimer on the Forum post mentioning that it could be bannable, however no one has gotten banned for it, as well as the Forum post still being up in Hoyolabs serving as proof for that.

So far after a year of the project being used, no one has gotten banned including mine, so it should be relatively safe, but I don't really offer any promises, just take it with a grain of salt.

**Comment by Jakeisaweeb** [comment]
Ok thanks!
