### ISSUE TITLE
v3.1.1 - Malicious behavior

### ISSUE THREAD

**Issue by gionata-bisciari** [sabihoshi/GenshinLyreMidiPlayer#22]
I liked this tool a lot but unfortunately v3.1.1 contains a spyware/malware 😢
[https://www.sophos.com/en-us/threat-center/threat-analyses/viruses-and-spyware/Mal~EncPk-MK/detailed-analysis](url)
![Immagine 2022-03-05 034533](https://user-images.githubusercontent.com/15786737/156864858-42d41f5f-6eaa-40f9-ad9c-6a68e6907415.png)

**Comment by sabihoshi** [comment]
The code is open source, feel free to look into it yourself and then compile it yourself.
This "antivirus" is saying it's malware probably because it's not signed, not because it is actually malware.
