### ISSUE TITLE
is there any way to change the transpose after selecting one for a file??

### ISSUE THREAD

**Issue by chryslxm** [sabihoshi/GenshinLyreMidiPlayer#24]
a lot of my songs sound messy and i cant find any options to improve it anywhere. from what i can tell, the transpose setting in the settings menu does not affect the ones that had previously had a transpose setting selected for it. plz let me know if theres a way to fix this!!

**Comment by sabihoshi** [comment]
If you remove the song and add it again, you should be able to pick whether to shift up or down for that particular song
