### ISSUE TITLE
Add support to Sumeru's Vintage Lyre

### ISSUE THREAD

**Issue by MobApache** [sabihoshi/GenshinLyreMidiPlayer#26]
Notes on the vintage lyre are different

**Comment by sabihoshi** [comment]
I haven't unlocked that Lyre yet but I will look at it. Thank you for telling me

**Comment by sabihoshi** [comment]
Vintage Lyre is now supported in the [latest release](https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v4.0.1)
