### ISSUE TITLE
I don't see the icon of button

### ISSUE THREAD

**Issue by MoralBook** [sabihoshi/GenshinLyreMidiPlayer#27]
It's just square..

**Comment by MoralBook** [comment]
It's just a square..

**Comment by MoralBook** [comment]
And one request..I hope I could seperate the midi files into groups(like Youtube playlist?) so I can find the song which I want to play more easily..

**Comment by mariolecker** [comment]
Same, icons are not shown on Windows 10

**Comment by sabihoshi** [comment]
Do you have a screenshot of which button it is? I'm on Windows 11 so I can't test it out, I had a Windows 10 machine, but it was updated to the latest version so that may be why. (22H2)

**Comment by abriginets** [comment]
@sabihoshi something like that.

<details>
  <summary>Image</summary>

![image](https://user-images.githubusercontent.com/17240507/191143518-819eb62e-6446-4a58-b069-8679dcf0b218.png)

</details>
<details>
  <summary>Image</summary>

![image](https://user-images.githubusercontent.com/17240507/191143569-5a46be74-c221-459e-aa3d-c8b4961949ff.png)

<details>

**Comment by sabihoshi** [comment]
Thanks, what build version of Windows do you have by the way? You can check by doing `winver` in Run. 
![image](https://user-images.githubusercontent.com/25006819/191143928-5c7d36ca-5a4f-45f7-883c-2742d7c650ae.png)

**Comment by abriginets** [comment]
21H2 (19044.2006)

**Comment by sabihoshi** [comment]
> And one request..I hope I could seperate the midi files into groups(like Youtube playlist?) so I can find the song which I want to play, more easily..

If you want to group them, it's always grouped by their filename's first letter, so you can group it by renaming the files to 1_Song 1_Song and 2_Song 2_Song etc.

**Comment by sabihoshi** [comment]
This has been fixed in [v4.0.2](https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v4.0.2) you may download it there! Thank you for reporting.
