### ISSUE TITLE
Invisible buttons on first execution

### ISSUE THREAD

**Issue by mariolecker** [sabihoshi/GenshinLyreMidiPlayer#29]
When starting for the first time, the modal for finding the GenshinImpact.exe comes up, but there are no buttons visible.
It is possible to click on the hidden buttons, so that one can select the right location.

**Windows Version:** 21H1 (Build 19043.2006)

**Side question:** Do you have a good website, where to find good midi files for the game? Many midis don't work that well with the lyre.
Thank you for making such an awesome tool! 

![missingbuttons](https://user-images.githubusercontent.com/37740324/191345983-c3ae2a6a-9544-4504-bab8-aad85beb5cab.png)

**Comment by sabihoshi** [comment]
This should be fixed now because of #30, thank you to @DavG25!
