### ISSUE TITLE
support other languages

### ISSUE THREAD

**Issue by pdf114514** [sabihoshi/GenshinLyreMidiPlayer#3]
This doesn't work in Japanese, Chinese, or Korean.
I think it's because the name of the window is not "Genshin Impact"
![japanese](https://user-images.githubusercontent.com/57948770/113511393-8099d700-959a-11eb-8b6a-bb6b318ade52.png)

**Comment by sabihoshi** [comment]
You're right, I'm basing it off by the window name which is wrong, may I ask if it's named `GenshinImpact.exe` on other languages too? I should change it to getting the process name instead of the window name.

**Comment by sabihoshi** [comment]
This is now fixed, you can head to [v1.3.3](https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v1.3.3) to get the fix
