### ISSUE TITLE
Unable to use test mode in Win10 

### ISSUE THREAD

**Issue by jk4989** [sabihoshi/GenshinLyreMidiPlayer#33]
When I start the application a tab pops up saying **ArgumentException There is no 'Microsoft GS Wavetable Synth'. (Parameter name)**
How can I fix this issue and what is Microsoft GS Wavetable Synth?

**Comment by sabihoshi** [comment]
That Wavetable Synth is what the program uses to generate the MIDI sounds, think of it like an instrument pack for the MIDI sounds, without it, there's no sound pack the program can use to produce the sounds. I tried looking for how to install it, but it seems like it comes from the sound card, so you may try finding the relevant drivers for your sound card, in my case its Realtek HD Audio drivers.

**Comment by jk4989** [comment]
Thank you so much for your reply. It worked with just **reinstalling my soundcard drivers**. It was a weird error because there was no error or any issues with using midi elsewhere but this lyre application. I wish it could help others who are struggling with the same issue.
