### ISSUE TITLE
An error occurs when pausing with Transpose enabled/disabled then play

### ISSUE THREAD

**Issue by pdf114514** [sabihoshi/GenshinLyreMidiPlayer#5]
https://user-images.githubusercontent.com/57948770/114367528-7ccc0d00-9bb7-11eb-8f62-f38d8a4319ac.mp4

**Comment by sabihoshi** [comment]
I think this issue happens even without you having to play first, it's missing logic where if transpose is off and the key is missing, it will just ignore the note. Instead it will try to get that index, which would be `-1` and throw.

**Comment by sabihoshi** [comment]
The hotfix is now live and you can get a release of it over at [v1.5.4](https://github.com/sabihoshi/GenshinLyreMidiPlayer/releases/tag/v1.5.4)
