### ISSUE TITLE
Bug in "azerty" keys

### ISSUE THREAD

**Issue by shadowxdgamer** [sabihoshi/GenshinLyreMidiPlayer#8]
In **azerty** keys there is a small bug a "wrong letter" that should be changed
![bug](https://user-images.githubusercontent.com/64868173/117379168-cbc34480-aece-11eb-9bf8-1f60b9a0d35f.png)
well im not a programmer(im planning to learn in the near future ;D) and i dont know how to fix it and thought of informing you

Also is it possible to make a **windows 7** version of the **GenshinLyreMidiPlayer** my friend has a windows 7 and i would like to try this tool with him playing duet songs. (as long as it does the main core thing that's good doesn't have to be polished or anything)

This tool is so good and so accurate good job on that, i will be making youtube videos and make sure to mention you in the description, also have a look at my request. Peace and have a good day 😉

**Comment by sabihoshi** [comment]
Thanks for reporting, I totally missed that.

And for Windows 7, does it not work there? Is there any error he gets when he tries to run it? It's published to win-x86 and win-x64 so it should work on Windows 7 as well

**Comment by shadowxdgamer** [comment]
Thank you for replying, actually no error shows up it straight up crashes i tried both x64 and x86 now with the same result

https://user-images.githubusercontent.com/64868173/117509692-9b3ce280-af82-11eb-9cb7-12cde67816f7.mp4

I will try the both the two things you shared and tell you if it works after. i dont know if he has them installed
![bug](https://user-images.githubusercontent.com/64868173/117510428-f7eccd00-af83-11eb-950c-26cdd96eaec7.PNG)

Thanks again and if it doesn't work, there is no need to have a burnout over it :D

**Comment by shadowxdgamer** [comment]
Hello quick update. i have just downloaded an old version and tested and it works :D

![image](https://user-images.githubusercontent.com/64868173/117516944-7f413d00-af92-11eb-955b-d536ecb51307.png)

**versions from 1.8.3 and below work. I think it has something to do with the new **media control****

![image](https://user-images.githubusercontent.com/64868173/117517070-c29bab80-af92-11eb-98b9-fe9b522ef386.png)

I have thought of testing  yoroshikun's Genshin Lyre Player and when it worked i had the idea to test the old versions

![image](https://user-images.githubusercontent.com/64868173/117517248-5a00fe80-af93-11eb-8849-475f06d1a611.png)

I think the issue is closed now :D, saddly the newer version 1.9.1 doesn't work and crashes

**Comment by sabihoshi** [comment]
Yeah that should do it, Windows 7 doesn't have the native Media Controls. I can just disable it when you're not running Windows 10, but in reality v1.9.1's new functionality is only the Media Controls so the older version should work the same way anyways.

Thank you for figuring it out! I'll implement a version where SMTC is disabled when not running Windows 10.

**Comment by shadowxdgamer** [comment]
Okay, thanks and good luck on your future projects :p
